name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"

jobs:
  refresh:
    name: refresh jsdelivr cache
    runs-on: ubuntu-latest

    steps:
      - name: check and download latest
        run: |
          latest=$(curl -sS https://github.com/justjavac/dvm/releases/latest | sed 's/.*v\(.*\)\".*/\1/g')
          if [ ! "$latest" ]; then
            echo "Error: Unable to find latest dvm release on GitHub."
            exit 1
          fi
          if [ $(cat latest.txt) = "${latest}" ]; then
            echo "No new version"
            exit 0
          fi
          for archive in "dvm-x86_64-pc-windows-msvc.zip" "dvm-x86_64-apple-darwin.zip" "dvm-x86_64-unknown-linux-gnu.zip"; do
              download_uri="https://github.com/justjavac/dvm/releases/download/v${latest}/${archive}"
              curl --fail --location  --output "$archive" "$download_uri"
          done
          printf "${latest}" > latest.txt

      - name: Push to GitHub
        run: |
          if [[ -z $(git status -s) ]]; then
            echo "without changes"
            exit 0
          if

          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          latest=$(cat latest.txt)
          git commit -am "release ${latest}"
          git push

      - name: refresh
        run: |
          curl -sSL https://purge.jsdelivr.net/gh/justjavac/dvm_releases/dvm-x86_64-apple-darwin.zip
          curl -sSL https://purge.jsdelivr.net/gh/justjavac/dvm_releases/dvm-x86_64-pc-windows-msvc.zip
          curl -sSL https://purge.jsdelivr.net/gh/justjavac/dvm_releases/dvm-x86_64-unknown-linux-gnu.zip
          curl -sSL https://purge.jsdelivr.net/gh/justjavac/dvm_releases/latest.txt
